# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 2ee2c93
_src_path: https://github.com/vivienm/copier-rust
copyright_holder: Vivien Maisonneuve
copyright_year: 2024
forge: github
github_repo: rbk-db
github_user: vivienm
license: MIT
package_name: rbk-db
project_description: Import the Rebrickable LEGO database into SQLite.
project_name: rbk-db
project_type: application
rust_toolchain: stable
user_name: Vivien Maisonneuve
